---
title: "3D_fishing_proces_readme"
author: "jmenblaz - Javier Menéndez-Blázquez"
format: html
editor: visual
---

## 1- Fishing effort data-set

Global Fishing Watch was used as a open-source fishing effort (hours) data to extract the fishing activities in the study area. In that case we used the mean of fishing effort for 12 years, from 2012 to 2024 (<https://globalfishingwatch.org/dataset-and-code-fishing-effort/>). (`raw` files)

The yearly mean fishing effort for all this period has been used as a input for the fishing 3D processing and analysis presented here. A Geotiff file are provided by fishing gear type of interest at 0.1º of resolution (\~ 10x10 km) for the study area. Also, a `.csv` and `png` files are generated during this process

This data represent a 2D fishing effort for its overlap with 2D kde calculated.

see GFW folder in order to download and processing data for further analysis

## 2- Fishing effort 3D processing

From 2D fishing effort to 3D using a specific metier or fishing gear / art specific depth.

Media anual de valores de pesca (1x1 Km^2^): GMTDS, Global Fishing Watch

1\) Se han eliminado outliers o valores de pixel superiores al 95% para delimitar zonas portuarias dado que los valores de esfuerzo pesquero vienen dados por AIS

As an output, per each organismID and distinct fishing_gear\
`organismID_3d_fishing-effort_fishing_gear.tif`

## 3- Fishing effort 3D

Para calcular el volumen ocupado por la actividad pesquera en cada tramo de profundidad se han obtenido todos los valores de esfuerzo pesquero del área (salvo aquellos \> al 95% de los datos) y se han resampleado en una escala de 0-1 (con 1 siendo el máximo de esfuerzo). Esto se ha realizado para poder calcular el esfuerzo peaquero como si fuese Utilization distribution (UD) como el resultado de un Kernel. Con dicho valores se ha podido calcular el volumen ocupado en función del esfuerzo de pesca para cada voxel gracias a las función `volumeUD` del paquete `fishtrack3D`

ESPECICIAR AQUI EL PROCESADO DE TRALERS Y DE LONGLINES

*Los valores de los raster "organismID_fishing-effort_3d_volume" presentan valores de 0-1, con la proporcion de volumen ocupado en ese voxel en función del esfuerzo pesquero. A mayor esfuerzo pesquero, mayor volumen ocupado. Siguiendo la lógica de los valores de Kernel Density Estimation y el calculo del volumen. A mayor presencia mayor ocupación*

## 4 - Fishing effort 3D outputs / results

Summary of volumes per UD (50, 75, 95%) and total distribution volume for all `organismID` processed are gathered in `3kde_fishing_overlap_results.csv`

Also, per `organismID` thee diferenrt spatial files (raster) were generated:

1\) `organismID_kde_fishing_interact.tif`

Interaction between kde and fishing effort per organism. Multiply kde and fishing effort values to identify areas with high impact: *high impact = high kde values and high fishing effort.* As a measure of areas with high fishing effort and high presence of organisms

2\) `organismID_kde_fishing_intersect.tif`

per each organismID, provide the volume in which there is an impact of fishing effort (dintersection between total volume voxel and the fishing effort voxel)

3\) `organismID_kde_fishing_difference.tif`

per each organismID, provide the volume without impact of fishing effort (diference between total volume voxel and the fishing effort voxel)
