---
title: "readme_tracking"
author: "J.Ménendez-Blázquez | @jmenblaz"
format: html
editor: visual
---

#### Tracking data processing levels

*From locations and temperature-deprth records loggers*

Locations (l`oc`)

-   `L0` - standardized data (following Sequeira et al., 2021 fields nomenclature)

-   `L1` -

-   `L2`

-   `L3` - Pre processed L2 files in order to conduct 3D analysis (calculate position errors)

Temperature-depth recorder (`ttdr`)

-   `L0` - standardized data

-   `L1` - post-processing TTDR data:

    -   Zero offset correction + Identification of ascent and descent phases

    -   Estimation of depth and temperature errors

    -   Temperature QC (regional test)

    -   Interpolate locations from SSM

    -   Day and night information

-   `L2` - filtering and cleaning L1 TTDR files: remove records with NA in `time` and `depth` files

-   `L3` - pre-processing **L1\*** for adding night/day position (as well as dusk time).

#### Confidence intervals (CI) for predicted loc positions (SSM)

Values such as `lat.025`, `lat.975,` `lon.025`, `lon.975` refer to confidence intervals (CI) ranging from 2.5% to 97.5% for the latitude coordinates (and similarly for longitude).

These CIs do not seem to be directly included in your `data.frame` called `ssm`. However, you can calculate them using the `latitude` and `y.se` columns (or `longitude` and `x.se` for longitude), assuming the standard deviations (`x.se` and `y.se`) are used to compute the intervals under a normal distribution.

Add after regularize position in State Space Models (03_regularize_ssm.R)

|                  |                  |
|------------------|------------------|
| Confident levels | Critic value (Z) |
| 90%              | 1.645            |
| 95%              | 1.96             |
| 99%              | 2.576            |

Using `aniMotum` R package, after applied the State Space Model (SSM), the output data provided contains a `x` and `y` fields name, which correspond to Mercator proyectos coordinates (*see package documentation for detail information*). Due, `x.se` and `y.se` correspond to location measures errors in meters.
